### PR TITLE
Make compliant for Ruby 3.x

### PR DESCRIPTION
**Pull request by jbrodie**
Updated http-parser-lite gem to Ruby 3.3 compliant gem.
Removed deprecations / errors around the removal of exists? in Ruby 3.2
Closes #249
Closes #242

### CODE REVIEW

**Comment by jbrodie** [comment]
@iffyuva 

Can someone please review this?  I would love to get a new version of the gem cut and available to work on Ruby 3.x

**Comment by iffyuva** [comment]
@jbrodie thanks for the PR. 

@swrobel would you like to cut a new release? Thanks

**Comment by jbrodie** [comment]
@swrobel I have used it on > Ruby 3.x only at this point.
I can't say I have anything else below that to test it against, and I think anything below 3.x is out of support anyways.
3.0 is on the way out, 3.1 will be minimum.
I would think leaving it restricted to 3.0 would be fine as I can vouch for that working.

https://www.ruby-lang.org/en/downloads/branches/

**Comment by jbrodie** [comment]
@swrobel 
I have added the gemspec ruby restriction, as well as changelog record.
Also, bumped to 2.0.0 version as this is something of a major change and it just felt like the right thing to do.

**Comment by swrobel** [comment]
> would you like to cut a new release?

@iffyuva I don't believe I have rubygems permission, so someone from your org will have to release the gem, but it should be good to go

**Comment by jbrodie** [comment]
@swrobel 
@iffyuva

Any update on when to expect this to be release on rubygems?

**Comment by jbrodie** [comment]
@swrobel
@iffyuva

Hey guys,
I don't mean to pester but any chance we can get this new version on Rubygems?

**Comment by iffyuva** [comment]
@jbrodie I have cut a new release. Thanks for the PR. Cheers 👍

**Comment by jbrodie** [comment]
Awesome.  TY.

**Pull request merged**
